### ISSUE TITLE
Typo in tests

### ISSUE THREAD

**Issue by barkls** [phys201/qd_laser_dynamics#31]
Test inference has a test class inherited from `Testcase` instead of `TestCase`. Clearly these tests weren't run before pushing to GitHub.
```
======================================================================
ERROR: Failure: NameError (name 'Testcase' is not defined)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Solomon\miniconda3\envs\phys201\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\Solomon\miniconda3\envs\phys201\lib\site-packages\nose\loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "C:\Users\Solomon\miniconda3\envs\phys201\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\Solomon\miniconda3\envs\phys201\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\Solomon\miniconda3\envs\phys201\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "C:\Users\Solomon\miniconda3\envs\phys201\lib\imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Solomon\qd_laser_dynamics\qddynamics\tests\test_inference.py", line 21, in <module>
    class TestPriors_limit(Testcase):
NameError: name 'Testcase' is not defined
```

**Comment by barkls** [comment]
Similarly, there's a typo in `test_likelihood` where it tries to import "qddyamics"

**Comment by barkls** [comment]
There's no point including tests if you don't run them.

**Comment by hkwarner** [comment]
reverted test classes to repair bugs (#36)
